<?php
/**
 * @package      Joomproject
 * @subpackage   Tasks
 *
 * @author       JoomBoost
 * @copyright    Copyright (C) 2012-2018 JoomBoost. All rights reserved.
 * @license      http://www.gnu.org/licenses/gpl.html GNU/GPL, see LICENSE.txt
 */

defined('_JEXEC') or die();

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Session\Session;
use Joomla\CMS\MVC\Controller\FormController;



class JPtasksControllerTask extends FormController
{
    /**
	 * The prefix to use with controller messages.
	 *
	 * @var    string
	 */
    protected $text_prefix = "COM_JOOMPROJECT_TASK";


    /**
     * Class constructor.
     *
     * @param     array              $config    A named array of configuration variables
     * @return    jcontrollerform
     */
    public function __construct($config = array())
    {

        // auto-checking feature
        if(\Joomla\CMS\Component\ComponentHelper::getParams('com_jptasks')->get('task_autochecking',0))
            JoomprojectHelperFrontend::autoCheckin('jp_tasks',Factory::getApplication()->input->getInt('id'));


        parent::__construct($config);
    }

    /**
     * Proxy for getModel.
     *
     * @param     string    $name      The name of the model.
     * @param     string    $prefix    The prefix for the PHP class name.
     * @return    jmodel
     */
    public function getModel($name = 'Task', $prefix = 'JPtasksModel', $config = array('ignore_request' => true))
    {
        $model = parent::getModel($name, $prefix, $config);

        return $model;
    }

	/**
	 * Method to run batch operations.
	 *
	 * @param   object  $model  The model.
	 *
	 * @return  boolean   True if successful, false otherwise and internal error is set.
	 *
	 * @since   1.1
	 */
	public function batch($model = null)
	{
		Session::checkToken() or jexit(Text::_('JINVALID_TOKEN'));

		// Set the model
		$model = $this->getModel('Task', '', array());

		// Preset the redirect
		$this->setRedirect(Route::_('index.php?option=com_jptasks&view=tasks' . $this->getRedirectToListAppend(), false));

		return parent::batch($model);
	}

    public function save($key = null, $urlVar = null)
    {
        return parent::save($key, $urlVar); // TODO: Change the autogenerated stub
    }


}
