MOD_JPACTIVITIES_SITE = "JPactivities"
MOD_JPACTIVITIES_SITE_XML_DESCRIPTION = "JPactivities Module for the Joomla site frontend."
MOD_JPACTIVITIES_SITE_INPUT_SEARCH_PLACEHOLDER = "Search for title or user"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_SELECT_EXTENSION = "- Select Extension -"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_SELECT_LOCATION = "- Select Location -"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_SELECT_EVENT = "- Select Event -"
MOD_JPACTIVITIES_SITE_FILTER_SEARCH_DESC = "Search title. Prefix with author: to search for a user."
MOD_JPACTIVITIES_SITE_NO_MATCHING_RESULTS = "No Matching Results."

; Events
COM_JPACTIVITIES_EVENT_SAVE_NEW = "Create"
COM_JPACTIVITIES_EVENT_SAVE_UPDATE = "Update"
COM_JPACTIVITIES_EVENT_PUBLISH = "Publish"
COM_JPACTIVITIES_EVENT_UNPUBLISH = "Unpublish"
COM_JPACTIVITIES_EVENT_ARCHIVE = "Archive"
COM_JPACTIVITIES_EVENT_TRASH = "Trash"
COM_JPACTIVITIES_EVENT_DELETE = "Delete"

; Relative date time
COM_JPACTIVITIES_DT_MONTH_AGO = "%s month ago"
COM_JPACTIVITIES_DT_MONTHS_AGO = "%s months ago"
COM_JPACTIVITIES_DT_DAY_AGO = "%s day ago"
COM_JPACTIVITIES_DT_DAYS_AGO = "%s days ago"
COM_JPACTIVITIES_DT_HOUR_AGO = "%s hour ago"
COM_JPACTIVITIES_DT_HOURS_AGO = "%s hours ago"
COM_JPACTIVITIES_DT_MIN_AGO = "%s minute ago"
COM_JPACTIVITIES_DT_MINS_AGO = "%s minutes ago"
COM_JPACTIVITIES_DT_JUST_NOW = "Just now"

; Configuration
MOD_JPACTIVITIES_SITE_FIELD_LIST_LIMIT_LABEL = "Count"
MOD_JPACTIVITIES_SITE_FIELD_LIST_LIMIT_DESC = "The amount of activities to show"
MOD_JPACTIVITIES_SITE_CONFIG_GROUP_ACTIVITY_LABEL = "Group Activity"
MOD_JPACTIVITIES_SITE_CONFIG_GROUP_ACTIVITY_DESC = "Select whether to group activities of the same type by the same user into a single record."
MOD_JPACTIVITIES_SITE_FIELD_OPTION_PERIOD_0 = "Do not group activity"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_PERIOD_1 = "Group within 1 minute"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_PERIOD_5 = "Group within 5 minutes"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_PERIOD_15 = "Group within 15 minutes"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_PERIOD_30 = "Group within 30 minutes"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_PERIOD_60 = "Group within 60 minutes"
MOD_JPACTIVITIES_SITE_FIELD_AUTHORS_LABEL = "Authors"
MOD_JPACTIVITIES_SITE_FIELD_AUTHORS_DESC = "A filter for the authors"
MOD_JPACTIVITIES_SITE_FIELD_VALUE_ANYONE = "Show from anyone"
MOD_JPACTIVITIES_SITE_FIELD_VALUE_BY_ME = "Show my activity only"
MOD_JPACTIVITIES_SITE_FIELD_VALUE_NOT_BY_ME = "Show from anyone but me"
MOD_JPACTIVITIES_SITE_FIELD_EXTENSION_LABEL = "Extensions"
MOD_JPACTIVITIES_SITE_FIELD_EXTENSION_DESC = "A filter for the extensions"
MOD_JPACTIVITIES_SITE_FIELD_LOCATION_LABEL = "Location"
MOD_JPACTIVITIES_SITE_FIELD_LOCATION_DESC = "A filter for the location"
MOD_JPACTIVITIES_SITE_FIELD_VALUE_ALL_LOCATIONS = "All Locations"
MOD_JPACTIVITIES_SITE_FIELD_SHOW_FILTER_SEARCH_LABEL = "Show Search"
MOD_JPACTIVITIES_SITE_FIELD_SHOW_FILTER_SEARCH_DESC = "Set whether to show a search field or not"
MOD_JPACTIVITIES_SITE_FIELD_SHOW_FILTER_EXTENSION_LABEL = "Show Extension Filter"
MOD_JPACTIVITIES_SITE_FIELD_SHOW_FILTER_EXTENSION_DESC = "Set whether to show a filter for extensions or not"
MOD_JPACTIVITIES_SITE_FIELD_SHOW_FILTER_EVENT_LABEL = "Show Event Filter"
MOD_JPACTIVITIES_SITE_FIELD_SHOW_FILTER_EVENT_DESC = "Set whether to show a filter for events or not"
MOD_JPACTIVITIES_SITE_CONFIG_USER_LINK_LABEL = "User Link"
MOD_JPACTIVITIES_SITE_CONFIG_USER_LINK_DESC = "Set the user profile link destination"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_NOLINK = "No Link"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_JOOMLA = "Joomla"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_CB = "Community Builder"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_JOMSOCIAL = "Jomsocial"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_KUNENA = "Kunena"
MOD_JPACTIVITIES_SITE_FIELD_OPTION_JOOMPROJECT = "JoomProject"
MOD_JPACTIVITIES_SITE_CONFIG_DATE_RELATIVE_LABEL = "Relative Date"
MOD_JPACTIVITIES_SITE_CONFIG_DATE_RELATIVE_DESC = "Show dates in a relative format. For example: 5 minutes ago"
JOPTION_ALL_EXTENSIONS = "All Extensions"