<?php
/**
 * @package		JoomProject
 * @copyright	2013-2019 JoomBoost, joomboost.com
 * @license		GNU/GPL http://www.gnu.org/copyleft/gpl.html
 */

defined('_JEXEC') or die;

use Joomla\CMS\Language\Text;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Component\ComponentHelper;
use Joomla\CMS\Form\FormHelper;
use Joomla\CMS\Layout\FileLayout;
use Joomla\CMS\Form\Field\CategoryField;
FormHelper::loadFieldClass('Category');



class JFormFieldJPCategory extends CategoryField
{
    public $type = 'jpcategory';

    /**
     * Get the renderer
     *
     * @param   string  $layoutId  Id to load
     *
     * @return  FileLayout
     *
     * @since   3.5
     */


    protected function getOptions()
    {
        // disable root category from config

        $options = parent::getOptions(); // TODO: Change the autogenerated stub

        if (!ComponentHelper::getParams('com_jpprojects')->get('hide_root_category',0))
        {
            array_unshift($options, HTMLHelper::_('select.option', '0', Text::_('JGLOBAL_ROOT')));
        }

        return $options;

    }



    protected function getRenderer($layoutId = 'default')
    {



        $renderer = new FileLayout($layoutId, null,
            [
                "client" => 1,
                'component' => 'com_joomproject'
            ]
        );

      /*  if(Factory::getApplication()->isClient('administrator')){
            $layoutPaths = $this->getLayoutPaths();

            if ($layoutPaths)
            {
                $renderer->setIncludePaths($layoutPaths);
            }
        } */

        return $renderer;
    }
}
