<?php
/**
 * @package		JoomProject
 * @copyright	2013-2019 JoomBoost, joomboost.com
 * @license		GNU/GPL http://www.gnu.org/copyleft/gpl.html
 */

defined('_JEXEC') or die;

use Joomla\CMS\Uri\Uri;
use Joomla\CMS\Form\FormHelper;
use Joomla\CMS\Layout\FileLayout;
use Joomla\CMS\Filesystem\File;
use Joomla\CMS\Form\Field\FileField;
FormHelper::loadFieldClass('File');



class JFormFieldJPFile extends FileField
{
    public $type = 'jpfile';

    /**
     * Get the renderer
     *
     * @param   string  $layoutId  Id to load
     *
     * @return  FileLayout
     *
     * @since   3.5
     */
    protected function getRenderer($layoutId = 'default')
    {

        $renderer = new FileLayout($layoutId, null,
            [
                "client" => 1,
                'component' => 'com_joomproject'
            ]
        );

      /*  if(Factory::getApplication()->isClient('administrator')){
            $layoutPaths = $this->getLayoutPaths();

            if ($layoutPaths)
            {
                $renderer->setIncludePaths($layoutPaths);
            }
        } */

        return $renderer;
    }

    protected function getInput()
    {
        $input = parent::getInput(); // TODO: Change the autogenerated stub

        $value = $this->__get('value');
        $fieldName = $this->__get('name');
        $component = \Joomla\CMS\Factory::getApplication()->input->get('option','','string');

        // to display thumb for media
        if($fieldName == 'jform[file]' && $component == "com_jpdesigns"){ // mean media item
            $value = $this->form->getData()->get('file_name');
        }

        if(empty($value))
            return $input;

        $ext  = strtolower(File::getExt($value));

        // Check file extension
        $allowedExtensions = ['jpeg', 'jpg', 'png', 'gif','webp'];


        if (!in_array($ext, $allowedExtensions)) {

            return $input;
        }


        $projectId = $this->form->getData()->get('project_id');
        $title = $this->form->getData()->get('title');



        $subPath = $fieldName == 'jform[thumbnail]' ? 'thumbnails/' : '';
        $rootUrl = Uri::root();



        $thumb = <<<html
<div class="my-2">
<img 
    class="img-thumbnail" 
    src="{$rootUrl}images/com_joomproject/designs/project_$projectId/{$subPath}{$value}"                 
    alt="$title" style="width: 160px"
/>
</div>
html;

        return $input.$thumb;




    }


}
