<?php
/**
 * @package      Joomproject
 * @subpackage   Tasks
 *
 * @author       JoomBoost
 * @copyright    Copyright (C) 2012-2018 JoomBoost. All rights reserved.
 * @license      http://www.gnu.org/licenses/gpl.html GNU/GPL, see LICENSE.txt
 */

defined('JPATH_PLATFORM') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Form\FormHelper;
use Joomla\CMS\Form\Field\ListField;
FormHelper::loadFieldClass('list');


/**
 * Form Field class for selecting a task list.
 *
 */
class JFormFieldMilestones extends ListField
{
    /**
     * The form field type.
     *
     * @var    string
     */
    public $type = 'Milestones';

    protected $project;

    protected $milestone;

    public function getInput()
    {

        $project = (int) \Joomla\CMS\Factory::getApplication()->input->getInt('filter_project',0);
        // Load only if project filter is set
        if ($project <= 0) return '';

        return parent::getInput(); // TODO: Change the autogenerated stub
    }


    /**
     * Method to get the field list options markup.
     *
     * @return    array      $options      The list options markup.
     */
    public function getOptions() {

        $db = Factory::getDbo();
        $query = $db->getQuery(true);

        $project = (int) \Joomla\CMS\Factory::getApplication()->input->getInt('filter_project',0);


        // Load only if project filter is set
        if ($project <= 0) return array();

        // Construct the query
        $query->select('m.id AS value, m.title AS text')
            ->from('#__jp_milestones AS m')
            ->join('INNER', '#__jp_tasks AS a ON a.milestone_id = m.id')
            ->where('a.project_id = ' . $db->quote($project))
            ->group('m.id')
            ->order('m.title');

        // Return the result
        $db->setQuery($query);
        $rows = $db->loadObjectList();
        $milestones = [];
        foreach($rows as $row){
            $milestones[] = $row->value;
        }
        // Merge any additional options in the XML definition.
        $options = array_merge(parent::getOptions(), $rows);
        return $options;
    }
}
