<?php
/**
 * @package      Joomproject
 * @subpackage   Tasks
 *
 * @author       JoomBoost
 * @copyright    Copyright (C) 2012-2018 JoomBoost. All rights reserved.
 * @license      http://www.gnu.org/licenses/gpl.html GNU/GPL, see LICENSE.txt
 */

defined('JPATH_PLATFORM') or die;
use Joomla\CMS\Factory;
use Joomla\CMS\Form\FormHelper;
use Joomla\CMS\Form\Field\ListField;

FormHelper::loadFieldClass('list');


/**
 * Form Field class for selecting a task list.
 *
 */
class JFormFieldTasks extends ListField
{
    /**
     * The form field type.
     *
     * @var    string
     */
    public $type = 'Tasks';

    protected $project;

    protected $milestone;



    public function getInput()
    {

        $project = (int) \Joomla\CMS\Factory::getApplication()->input->getInt('filter_project',0);
        // Load only if project filter is set
        if ($project <= 0) return '';

        return parent::getInput(); // TODO: Change the autogenerated stub
    }
    /**
     * Method to get the field list options markup.
     *
     * @return    array      $options      The list options markup.
     */
    public function getOptions() {

        $db = Factory::getDbo();
        $query = $db->getQuery(true);
        // Load only if project filter is set
        $project = (int) \Joomla\CMS\Factory::getApplication()->input->getInt('filter_project',0);

        if ($project <= 0) return array();

        // Construct the query
        $query->select('t.id AS value, t.title AS text')
            ->from('#__jp_task_lists AS t')
            ->join('INNER', '#__jp_tasks AS a ON a.list_id = t.id')
            ->where('a.project_id = ' . $db->quote($project))
            ->group('t.id')
            ->order('t.title');

        // Return the result
        $db->setQuery($query);
        $rows =  (array) $db->loadObjectList();

        // Merge any additional options in the XML definition.
        $options = array_merge(parent::getOptions(), $rows);
        return $options;
    }
}
