<?php
/**
* @package      Joomproject
* @subpackage   Comments
*
* @author       JoomBoost (eaxs)
* @copyright    Copyright (C) 2006-2012 JoomBoost. All rights reserved.
* @license      http://www.gnu.org/licenses/gpl.html GNU/GPL, see LICENSE.txt
**/

defined('_JEXEC') or die();

use Joomla\CMS\Factory;


jimport('joomproject.controller.form.json');


/**
 * Joomproject Comment Form Controller
 *
 */
class JPcommentsControllerForm extends JPControllerFormJson
{
    /**
     * The item view name.
     *
     * @var    string
     **/
    protected $view_item = 'form';

    /**
     * The list view name.
     *
     * @var    string
     **/
    protected $view_list = 'comments';


    /**
     * Method to get a model object, loading it if required.
     *
     * @param     string    $name      The model name. Optional.
     * @param     string    $prefix    The class prefix. Optional.
     * @param     array     $config    Configuration array for model. Optional.
     *
     * @return    object               The model.
     */
    public function &getModel($name = 'Form', $prefix = 'JPcommentsModel', $config = array('ignore_request' => true))
    {
        $model = parent::getModel($name, $prefix, $config);

        return $model;
    }


    /**
     * Method to check if you can add a new record.
     *
     * @param     array      $data    An array of input data.
     *
     * @return    boolean
     */
    protected function allowAdd($data = array())
    {

        // Get form input
        $project = isset($data['project_id']) ? (int) $data['project_id'] : JPApplicationHelper::getActiveProjectId();

        $user   = Factory::getApplication()->getIdentity();
        $asset  = 'com_jpcomments';
        $access = true;

        // Check if the user has access to the project
        if ($project) {
            // Check if in allowed projects when not a super admin
            if (!$user->authorise('core.admin')) {
                $access = in_array($project, JPUserHelper::getAuthorisedProjects());
            }

            // Change the asset name
            $asset  .= '.project.' . $project;
        }

        return ($user->authorise('core.create', $asset) && $access);
    }


    public function save($key = null, $urlVar = null)
    {

        parent::save($key, $urlVar); // TODO: Change the autogenerated stub
    }

}
