<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JLoader::register('JPremindersModelReminder', JPATH_ADMINISTRATOR . '/components/com_jpreminders/models/reminder.php');

/**
 * Reminder Model for an Reminder.
 *
 * @since  1.6
 */
class JPremindersModelForm extends JPremindersModelReminder
{

    public function save($data)
    {

        return parent::save($data); // TODO: Change the autogenerated stub
    }

}
